title: Yucheng Wang
name: Yucheng Wang
description: "M.Sc. in Digital FinTech @ NUS | Quant Researcher | Music Producer"
url: "https://wzwangyc.github.io"

minimal_mistakes_skin: "dark"
locale: "en-US"

author:
  name: "Yucheng Wang"
  avatar: "/assets/images/profile.jpg"
  bio: "Quant Scientist meets Artist.<br>M.Sc. @ **NUS**."
  location: "Singapore / Hangzhou"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wzwangyc@163.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wzwangyc"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/wzwangyc"
    - label: "NetEase Music"
      icon: "fas fa-fw fa-music"
      url: "https://y.music.163.com/m/artist?id=12057020"

# -----------------------
# 插件与构建设置 (Build Settings)
# -----------------------
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
